### ISSUE TITLE
References always include definition

### ISSUE THREAD

**Issue by nat-418** [VidocqH/lsp-lens.nvim#24]
In Python, the number of References always includes the definition of, e.g., the method, even when `include_declaration = false` in config  . I am not sure if this is intended or not, but I would prefer the number of _usages_ .

**Comment by VidocqH** [comment]
<img width="397" alt="image" src="https://github.com/VidocqH/lsp-lens.nvim/assets/16725418/dbce7ecb-673e-46f2-958d-21e3e556b1f2">

Seems like it's correct with pyright in a single file, the references number displayed is returned by LSP, I believe the issue is with LSP itself. You can verify this by checking with 'textDocument/references' query.
